### ISSUE TITLE
Provide AnuraSet v3

### ISSUE THREAD

**Issue by Bengt** [soundclim/anuraset#2]
This repository references AnuraSet v3, but Zenodo lists AnuraSet v2 and v3, only. So please provide AnuraSet v3 to enable reproduction.

**Comment by Bengt** [comment]
Ah, `fetcher.py` can download it.

**Comment by Bengt** [comment]
I uploaded the datasets to Hugging Face:

- <https://huggingface.co/datasets/AnuraSet/AnuraSet_v1.0.0>
- <https://huggingface.co/datasets/AnuraSet/AnuraSet_v1.0.0_raw>
- <https://huggingface.co/datasets/AnuraSet/AnuraSet_v2.0.0>
- <https://huggingface.co/datasets/AnuraSet/AnuraSet_v2.0.0_raw>

This means they can be downloaded programatically and quickly, like so:

```python
from datasets import load_dataset

anuraset_1 = load_dataset("AnuraSet/AnuraSet_v1.0.0")
anuraset_2 = load_dataset("AnuraSet/AnuraSet_v2.0.0")
anuraset_1_raw = load_dataset("AnuraSet/AnuraSet_v1.0.0_raw")
anuraset_2_raw = load_dataset("AnuraSet/AnuraSet_v2.0.0_raw")
```

For that to work, I had to split the audio files in the station folders additionally by date. ChatGPT and I came up with this implementation:

```python
import os
import re
from datetime import datetime

def move_files_to_subdirectories(source_dir):
    file_list = os.listdir(source_dir)
    
    date_pattern = re.compile(r'(\d{8})')
    
    for filename in file_list:
        match = date_pattern.search(filename)
        if match:
            date_str = match.group(1)
            file_path = os.path.join(source_dir, filename)
            
            if os.path.isfile(file_path):
                new_dir = os.path.join(source_dir, date_str)
                new_file_path = os.path.join(new_dir, filename)
                
                if not os.path.exists(new_dir):
                    os.makedirs(new_dir)
                
                os.rename(file_path, new_file_path)
                print(f"Moved {file_path} to {new_file_path}")

for source_directory in (
    "INCT20955",
    'INCT4',
    'INCT17',
    'INCT41',
):
    move_files_to_subdirectories(source_directory)
```

**Comment by Bengt** [comment]
I am downloading AnuraSet_v3 using the fetcher, but it takes about 1 day to download. Can you maybe provide another download server?

**Comment by Bengt** [comment]
The download of AnuraSet v3 keeps aborting:

```
/home/bengt/Downloads/github.com/soundclim/anuraset/venv/bin/python /home/bengt/Downloads/github.com/soundclim/anuraset/datasets/fetcher.py 
 11%|█         | 77349/692925 [2:46:27<22:04:41,  7.74 MB/s]
Traceback (most recent call last):
  File "/home/bengt/Downloads/github.com/soundclim/anuraset/datasets/fetcher.py", line 245, in <module>
    fetch_anuraset_v3()
  File "/home/bengt/Downloads/github.com/soundclim/anuraset/datasets/fetcher.py", line 184, in fetcher
    fetch_data(files, folder, data_size)
  File "/home/bengt/Downloads/github.com/soundclim/anuraset/datasets/fetcher.py", line 132, in fetch_data
    _get_file_data(fullpath, url)
  File "/home/bengt/Downloads/github.com/soundclim/anuraset/datasets/fetcher.py", line 92, in _get_file_data
    copyfileobj_withprogress(opener, data, response_size)
  File "/home/bengt/Downloads/github.com/soundclim/anuraset/datasets/fetcher.py", line 32, in copyfileobj_withprogress
    buf = fsrc.read(length)
  File "/usr/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

![image](https://github.com/soundclim/anuraset/assets/11575/9de9d42d-3733-47bd-8379-b7aeee96c0a9)

So, I am giving up for now. Please ping me, when a more usable download server becomes available.

**Comment by Bengt** [comment]
AnuraSet v2 is now also on Kaggle:

https://www.kaggle.com/datasets/bengtlueers/anuraset

**Comment by Bengt** [comment]
AnuraSet v2.0.0 Raw is now on Kaggle:

<https://www.kaggle.com/datasets/bengtlueers/anuraset-v2-raw>

**Comment by Bengt** [comment]
AnuraSet v1.0.0 Raw is now on Kaggle:

https://www.kaggle.com/datasets/bengtlueers/anuraset-v1-0-0-raw

**Comment by Bengt** [comment]
I cannot upload the non-raw v1.0.0 and v2.0.0 datasets to Kaggle, because I am affected by an issue where the website responds with a 404 error upon uploading the dataset: https://www.kaggle.com/discussions/general/403165

**Comment by ZhenxiongTang** [comment]
Hello, could you please provide a basic directory structure to organize the dataset?
